/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Cv2rsAmbulanceWlList {
    }
}
declare global {
    interface HTMLCv2rsAmbulanceWlListElement extends Components.Cv2rsAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLCv2rsAmbulanceWlListElement: {
        prototype: HTMLCv2rsAmbulanceWlListElement;
        new (): HTMLCv2rsAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "cv2rs-ambulance-wl-list": HTMLCv2rsAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface Cv2rsAmbulanceWlList {
    }
    interface IntrinsicElements {
        "cv2rs-ambulance-wl-list": Cv2rsAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cv2rs-ambulance-wl-list": LocalJSX.Cv2rsAmbulanceWlList & JSXBase.HTMLAttributes<HTMLCv2rsAmbulanceWlListElement>;
        }
    }
}
